artifact_uri: runs\mlflow/1/e6c96fce166b407eb580cf7ef93895bd/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: e6c96fce166b407eb580cf7ef93895bd
run_name: train6
run_uuid: e6c96fce166b407eb580cf7ef93895bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1704722796931
status: 1
tags: []
user_id: Alexkoh
